export const SIGNUP = "SIGNUP";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const GET_ME_REQUEST = "GET_ME_REQUEST";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_FAILURE = "GET_ME_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAIL";

export const CREATE_FOLDER_REQUEST = "CREATE_FOLDER_REQUEST";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const CREATE_FOLDER_FAILURE = "CREATE_FOLDER_FAILURE";

export const GET_ALL_FOLDERS_REQUEST = "GET_ALL_FOLDERS_REQUEST";
export const GET_ALL_FOLDERS_SUCCESS = "GET_ALL_FOLDERS_SUCCESS";
export const GET_ALL_FOLDERS_FAILURE = "GET_ALL_FOLDERS_SUCCESS";

export const RENAME_FOLDER_REQUEST = "RENAME_FOLDER_REQUEST";
export const RENAME_FOLDER_SUCCESS = "RENAME_FOLDER_SUCCESS";
export const RENAME_FOLDER_FAILURE = "RENAME_FOLDER_FAILURE";

export const DELETE_FOLDER_REQUEST = "DELETE_FOLDER_REQUEST";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";
export const DELETE_FOLDER_FAILURE = "DELETE_FOLDER_FAILURE";

export const CREATE_BOOKMARK_SUCCESS = "CREATE_BOOKMARK_SUCCESS";
export const CREATE_BOOKMARKS_REQUEST = "CREATE_BOOKMARKS_REQUEST";
export const CREATE_BOOKMARKS_FAILURE = "CREATE_BOOKMARKS_FAILURE";

export const DELETE_BOOKMARKS_REQUEST = "DELETE_BOOKMARKS_REQUEST";
export const DELETE_BOOKMARKS_SUCCESS = "DELETE_BOOKMARKS_SUCCESS";
export const DELETE_BOOKMARKS_FAILURE = "DELETE_BOOKMARKS_FAILURE";

export const GET_BOOKMARK_REQUEST = "GET_BOOKMARK_REQUEST";
export const GET_BOOKMARK_SUCCESS = "GET_BOOKMARK_SUCCESS";
export const GET_BOOKMARK_FAILURE = "GET_BOOKMARK_FAILURE";
