export const SIGNUP = "SIGNUP";
export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_FAILURE = "USER_REQUEST_FAILURE";
