export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST   ";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const GET_ME_REQUEST = "GET_ME_REQUEST";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_FAILURE = "GET_ME_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAIL";

export const CREATE_FOLDER_REQUEST = "CREATE_FOLDER_REQUEST";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const CREATE_FOLDER_FAILURE = "CREATE_FOLDER_FAILURE";

export const GET_ALL_FOLDERS_REQUEST = "GET_ALL_FOLDERS_REQUEST";
export const GET_ALL_FOLDERS_SUCCESS = "GET_ALL_FOLDERS_SUCCESS";
export const GET_ALL_FOLDERS_FAILURE = "GET_ALL_FOLDERS_SUCCESS";

export const RENAME_FOLDER_REQUEST = "RENAME_FOLDER_REQUEST";
export const RENAME_FOLDER_SUCCESS = "RENAME_FOLDER_SUCCESS";
export const RENAME_FOLDER_FAILURE = "RENAME_FOLDER_FAILURE";

export const DELETE_FOLDER_REQUEST = "DELETE_FOLDER_REQUEST";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";
export const DELETE_FOLDER_FAILURE = "DELETE_FOLDER_FAILURE";

export const CREATE_BOOKMARKS_SUCCESS = "CREATE_BOOKMARKS_SUCCESS";
export const CREATE_BOOKMARKS_REQUEST = "CREATE_BOOKMARKS_REQUEST";
export const CREATE_BOOKMARKS_FAILURE = "CREATE_BOOKMARKS_FAILURE";

export const DELETE_BOOKMARKS_REQUEST = "DELETE_BOOKMARKS_REQUEST";
export const DELETE_BOOKMARKS_SUCCESS = "DELETE_BOOKMARKS_SUCCESS";
export const DELETE_BOOKMARKS_FAILURE = "DELETE_BOOKMARKS_FAILURE";

export const GET_BOOKMARK_REQUEST = "GET_BOOKMARK_REQUEST";
export const GET_BOOKMARK_SUCCESS = "GET_BOOKMARK_SUCCESS";
export const GET_BOOKMARK_FAILURE = "GET_BOOKMARK_FAILURE";

export const SEARCH_FOLDER = "SEARCH_FOLDER";
export const SEARCH_FOLDER_FAILURE = "SEARCH_FOLDER_FAILURE";

export const FAVORITE_REQUEST = "FAVORITE_REQUEST";
export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS";
export const FAVORITE_FAILURE = "FAVORITE_FAILURE";

export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";

export const SHOW_FAVORITE = "SHOW_FAVORITE";

export const MOVE_BOOKMARK_REQUEST = "MOVE_BOOKMARK_REQUEST";
export const MOVE_BOOKMARK_SUCCESS = "MOVE_BOOKMARK_SUCCESS";
export const MOVE_BOOKMARK_FAILURE = "MOVE_BOOKMARK_FAILURE";

export const TOGGLE_VIEW = "TOGGLE_VIEW";
